sudo: true
dist: bionic
language: python
python:
 - '3.6'
services:
  - docker
before_install:
 - sudo apt-get update -q
 - |
   if [[ $TRAVIS_TAG ]]; then
   sh ci/build_debian.sh
   sh ci/test_debian.sh
   fi
script:
 - tox
 - gar --help
# - pytest --cov-report term-missing --cov=gar
after_success:
 - coveralls
 - ls ../*
before_deploy:
 - export DTAG=`echo ${TRAVIS_TAG#"v"}`
deploy:
 #tags: true
 provider: releases
 skip_cleanup: true
 file: 
    - ../gar_${DTAG}.tar.xz
    - ../python3-gar_${DTAG}_all.deb
 #draft: true 
 api_key: $GITHUB_TOKEN
 name: suvarchal
 email: suvarchal.kumar@gmail.com
 committer-from-gh: true
 on:
   tags: true

notifications:
  email: false
