sudo: true
language: python
python:
- '3.6'
before_install:
 - sudo add-apt-repository ppa:jonathonf/debhelper-11 -y
 - sudo apt-get update -q
 - sudo apt-get install fakeroot -y 
 - sudo apt-get install debhelper -y
 - sudo apt-get install dh-python -y
 - sudo apt-get install devscripts -y
 - sudo apt-get install python3-all -y
 - sudo apt-get install python3-setuptools -y
 - sudo apt-get install python3-pytest -y
 - travis_retry pip install click
script:
 - sudo apt-cache policy debhelper
 - debuild -us -uc -I -i
 - ls ../gar_*
 - mkdir -p upload/dist
 - mv ../gar_* upload/dist/
 - mv ../python3-gar_* upload/dist/
 - sudo apt-get install `ls upload/dist/python3-gar_*.deb` -y
 - gar --help
deploy:
 provider: pages
 skip_cleanup: true
 local_dir: ./upload
 github_token: $GITHUB_TOKEN
 name: suvarchal
 email: suvarchal.kumar@gmail.com
 committer-from-gh: true
 target_branch: gh-pages
