sudo: true
language: python
python:
 - '3.6'
before_install:
 - sudo add-apt-repository ppa:jonathonf/debhelper-11 -y
 - sudo apt-get update -q
 - sudo apt-get install fakeroot -y 
 - sudo apt-get install debhelper -y
 - sudo apt-get install dh-python -y
 - sudo apt-get install devscripts -y
 - sudo apt-get install python3-all -y
 - sudo apt-get install python3-setuptools -y
 - sudo apt-get install python3-pytest -y
 - travis_retry pip install pytest-cov
 - travis_retry pip install python-coveralls
 - travis_retry pip install click
 - travis_retry pip install tox
 - pip install -e .
script:
 #- tox
 - sudo apt-cache policy debhelper
 - debuild -us -uc -I -i
 - ls ../gar_*
 # - mkdir -p upload/dist
 # - mv ../gar_* upload/dist/
 #- mv ../python3-gar_* upload/dist/
 # - ls upload/
 # - ls upload/dist/
 #- sudo apt-get install `ls ./upload/dist/python3-gar_*.deb` -y
 - gar --help
 - pytest --cov-report term-missing --cov=gar
after_success:
 - coveralls 
deploy:
 #tags: true
 provider: releases
 skip_cleanup: true
 file: ../gar_0.0.1.tar.xz
 file: ../python3-gar_0.0.1_all.deb
 draft: True 
 github_token: $GITHUB_TOKEN
 name: suvarchal
 email: suvarchal.kumar@gmail.com
 committer-from-gh: true

 #on:
 #  tags: true

notifications:
  email: false
