sudo: true
language: python
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
python:
- '3.6'
before_install:
 - travis_retry pip install click
 - sudo apt-get install devscripts
 - sudo apt-get install python3-all
 - sudo apt-get install python3-setuptools
 - sudo apt-get install python3-pytest
script:
 - debuild -us -uc -I -i 
 - mkdir -p upload/dist
 - mv gar_* upload/dist
 - sudo apt-get install upload/dist/python3-gar_0.0.1_all.deb
 - gar --help
deploy:
 provider: pages
 skip_cleanup: true
 local_dir: ./upload
 github_token: $GITHUB_TOKEN
 name: suvarchal
 email: suvarchal.kumar@gmail.com
 committer-from-gh: true
 target_branch: gh-pages
